from boardfunc import *

# Print welcome message
print("Welcome to TicTacToe!")

# Get char
char = input("Would you like to be \'X\' or \'O\'?")

# TODO: Check if char is 'X' or 'O'

# Check whether or not to display instructions
a = input("Do you want instructions?").upper()
if a.startswith("Y"):
    drawInstructionBoard()

# Initialize and draw board
initBoard()
drawBoard()

def placement(a):
    a = input("Where do you want to play?")
    if a==17:
        print('   |   |')
        print(' ' + 'X ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
    if a==18:
        print('   |   |')
        print(' ' + ' ' + ' | ' + 'X ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
    if a==19:
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' X')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
    if a==14:
        print('   |   |')
        print(' ' + ' ' + ' | ' + 'X ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + 'X ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
    if a==15:
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + 'X ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
    if a==16:
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' X')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
    if a==11:
        print('   |   |')
        print(' ' + ' ' + ' | ' + 'X ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + 'X ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
    if a==12:
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' X' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
    if a==13:
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + 'X ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
    if a==29:
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + 'X ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print(' ')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
        print('-----------')
        print('   |   |')
        print(' ' + ' ' + ' | ' + ' ' + ' | ' + ' ')
        print('   |   |')
input()
